export const Tunings = Object.freeze([
  ["Standard", "E A D G B E"],
  ["Drop D", "D A D G B E"],
  ["Half Step Down", "D# G# C# F# A# D#"],
  ["Full Step Down", "D G C F A D"],
  ["1 and 1/2 Steps Down", "C# F# B E G# C#"],
  ["Double Drop D", "D A D G B D"],
  ["Drop C", "C G C F A D"],
  ["Drop C#", "C# G# C# F# A# D#"],
  ["Drop B", "B F# B E G# C#"],
  ["Drop A#", "A# F A# D# G C"],
  ["Drop A", "A E A D F# B"],
  ["Open D", "D A D F# A D"],
  ["Open D Minor", "D A D F A D"],
  ["Open G", "D G D G B D"],
  ["Open G Minor", "D G D G A# D"],
  ["Open C", "C G C G C E"],
  ["Open C#", "C# F# B E G# C#"],
  ["Open C Minor", "C G C G C D#"],
  ["Open E", "E G# D E B E"],
  ["Open E Minor7", "E B D G B E"],
  ["Open G Major7", "D G D F# B D"],
  ["Open A Minor", "E A E A C E"],
  ["Open A Minor7", "E A E G C E"],
  ["Open E", "E B E G# B E"],
  ["Open A", "E A C# E A E"],
  ["C Tuning", "C F A# D# G C"],
  ["C# Tuning", "C# F# B E G# C#"],
  ["Bb Tuning", "A# D# G# C# F A#"],
  ["A to A (Baritone)", "A D G C E A"],
  ["D A D D D D", "D A D D D D"],
  ["C G D G B D", "C G D G B D"],
  ["C G D G B E", "C G D G B E"],
  ["D A D E A D", "D A D E A D"],
  ["D G D G A D", "D G D G A D"],
  ["Open Dsus2", "D A D G A D"],
  ["Open Gsus2", "D G D G C D"],
  ["G", "D G D G B E"],
  ["Modal G", "D G D G C D"],
  ["Overtone", "C E G A# C D"],
  ["Pentatonic", "A C D E G A"],
  ["Minor Third", "C D# F# A C D#"],
  ["Major Third", "C E G# C E G#"],
  ["All Fourths", "E A D G C F"],
  ["Augmented Fourths", "C F# C F# C F#"],
  ["Slow Motion", "D G D F C D"],
  ["Admiral", "C G D G B C"],
  ["Buzzard", "C F C G A# F"],
  ["Face", "C G D G A D"],
  ["Four and Twenty", "D A D D A D"],
  ["Ostrich", "D D D D D D"],
  ["Capo 20", "C G D D# D D#"],
  ["Balalaika", "E A D E E A"],
  ["Charango", " G C E A E"],
  ["Cittern One", "C F C G C D"],
  ["Cittern Two", "C G C G C G"],
  ["Dobro", "G B D G B D"],
  ["Lefty", "E B G D A E"],
  ["Mandoguitar", "C G D A E B"],
  ["Rusty Cage", "B A D G B E"],
  ["Sitar", "C C G C G C F x C C B C D E F G A B C D E"],
]);
