export const Tunings = Object.freeze([
  { instrument: "Guitar", name: "Standard", tuning: "E A D G B E" },
  { instrument: "Guitar", name: "Drop D", tuning: "D A D G B E" },
  { instrument: "Guitar", name: "Half Step Down", tuning: "D# G# C# F# A# D#" },
  { instrument: "Guitar", name: "Full Step Down", tuning: "D G C F A D" },
  { instrument: "Guitar", name: "1 and 1/2 Steps Down", tuning: "C# F# B E G# C#" },
  { instrument: "Guitar", name: "Double Drop D", tuning: "D A D G B D" },
  { instrument: "Guitar", name: "Drop C", tuning: "C G C F A D" },
  { instrument: "Guitar", name: "Drop C#", tuning: "C# G# C# F# A# D#" },
  { instrument: "Guitar", name: "Drop B", tuning: "B F# B E G# C#" },
  { instrument: "Guitar", name: "Drop A#", tuning: "A# F A# D# G C" },
  { instrument: "Guitar", name: "Drop A", tuning: "A E A D F# B" },
  { instrument: "Guitar", name: "Open D", tuning: "D A D F# A D" },
  { instrument: "Guitar", name: "Open D Minor", tuning: "D A D F A D" },
  { instrument: "Guitar", name: "Open G", tuning: "D G D G B D" },
  { instrument: "Guitar", name: "Open G Minor", tuning: "D G D G A# D" },
  { instrument: "Guitar", name: "Open C", tuning: "C G C G C E" },
  { instrument: "Guitar", name: "Open C#", tuning: "C# F# B E G# C#" },
  { instrument: "Guitar", name: "Open C Minor", tuning: "C G C G C D#" },
  { instrument: "Guitar", name: "Open E", tuning: "E G# D E B E" },
  { instrument: "Guitar", name: "Open E Minor7", tuning: "E B D G B E" },
  { instrument: "Guitar", name: "Open G Major7", tuning: "D G D F# B D" },
  { instrument: "Guitar", name: "Open A Minor", tuning: "E A E A C E" },
  { instrument: "Guitar", name: "Open A Minor7", tuning: "E A E G C E" },
  { instrument: "Guitar", name: "Open E", tuning: "E B E G# B E" },
  { instrument: "Guitar", name: "Open A", tuning: "E A C# E A E" },
  { instrument: "Guitar", name: "C Tuning", tuning: "C F A# D# G C" },
  { instrument: "Guitar", name: "C# Tuning", tuning: "C# F# B E G# C#" },
  { instrument: "Guitar", name: "Bb Tuning", tuning: "A# D# G# C# F A#" },
  { instrument: "Guitar", name: "A to A (Baritone)", tuning: "A D G C E A" },
  { instrument: "Guitar", name: "D A D D D D", tuning: "D A D D D D" },
  { instrument: "Guitar", name: "C G D G B D", tuning: "C G D G B D" },
  { instrument: "Guitar", name: "C G D G B E", tuning: "C G D G B E" },
  { instrument: "Guitar", name: "D A D E A D", tuning: "D A D E A D" },
  { instrument: "Guitar", name: "D G D G A D", tuning: "D G D G A D" },
  { instrument: "Guitar", name: "Open Dsus2", tuning: "D A D G A D" },
  { instrument: "Guitar", name: "Open Gsus2", tuning: "D G D G C D" },
  { instrument: "Guitar", name: "G", tuning: "D G D G B E" },
  { instrument: "Guitar", name: "Modal G", tuning: "D G D G C D" },
  { instrument: "Guitar", name: "Overtone", tuning: "C E G A# C D" },
  { instrument: "Guitar", name: "Pentatonic", tuning: "A C D E G A" },
  { instrument: "Guitar", name: "Minor Third", tuning: "C D# F# A C D#" },
  { instrument: "Guitar", name: "Major Third", tuning: "C E G# C E G#" },
  { instrument: "Guitar", name: "All Fourths", tuning: "E A D G C F" },
  { instrument: "Guitar", name: "Augmented Fourths", tuning: "C F# C F# C F#" },
  { instrument: "Guitar", name: "Slow Motion", tuning: "D G D F C D" },
  { instrument: "Guitar", name: "Admiral", tuning: "C G D G B C" },
  { instrument: "Guitar", name: "Buzzard", tuning: "C F C G A# F" },
  { instrument: "Guitar", name: "Face", tuning: "C G D G A D" },
  { instrument: "Guitar", name: "Four and Twenty", tuning: "D A D D A D" },
  { instrument: "Guitar", name: "Ostrich", tuning: "D D D D D D" },
  { instrument: "Guitar", name: "Capo 20", tuning: "C G D D# D D#" },
  { instrument: "Guitar", name: "Balalaika", tuning: "E A D E E A" },
  { instrument: "Guitar", name: "Charango", tuning: " G C E A E" },
  { instrument: "Guitar", name: "Cittern One", tuning: "C F C G C D" },
  { instrument: "Guitar", name: "Cittern Two", tuning: "C G C G C G" },
  { instrument: "Guitar", name: "Dobro Open G", tuning: "G B D G B D" },
  { instrument: "Guitar", name: "Lefty", tuning: "E B G D A E" },
  { instrument: "Guitar", name: "Mandoguitar", tuning: "C G D A E B" },
  { instrument: "Guitar", name: "Rusty Cage", tuning: "B A D G B E" },

  // http://bassguitarplayerworld.com/advanced/alternate-tunings/
  // https://www.schoolofrock.com/resources/bass-guitar/beginners-guide-to-tuning-a-bass-guitar
  { instrument: "Bass", name: "Drop D", tuning: "D A D G" },
  { instrument: "Bass", name: "Drop C", tuning: "C G C F" },
  { instrument: "Bass", name: "Drop B", tuning: "B F# B E" },
  { instrument: "Bass", name: "D Standard", tuning: "D G C F" },
  { instrument: "Bass", name: "C to thirds", tuning: "C G C G" },
  { instrument: "Bass 5-String", name: "Standard", tuning: "B E A D G" },
  { instrument: "Bass 5-String", name: "High C", tuning: "E A D G C" },
  { instrument: "Bass 6-String", name: "Standard", tuning: "B E A D G C" },

  { instrument: "Ukulele", name: "C6", tuning: "G C E A" },
  { instrument: "Ukulele", name: "D6", tuning: "A D F# B" },

  { instrument: "Violin", name: "Standard", tuning: "G D A E" },
  { instrument: "Violin", name: "Cajun", tuning: "F C G D" },
  { instrument: "Violin", name: "Open G", tuning: "G D G B" },
  { instrument: "Violin", name: "Sawmill", tuning: "G D G D" },
  { instrument: "Violin", name: "Gee-Dad", tuning: "G D A D" },
  { instrument: "Violin", name: "Open D", tuning: "D D A D" },
  { instrument: "Violin", name: "High Bass, Old-Timey D", tuning: "A D A E" },
  { instrument: "Violin", name: "Cross A", tuning: "A E A E" },

  { instrument: "Russian Guitar", name: "Standard", tuning: "D G B D G B D" },
  { instrument: "Russian Guitar", name: "Classical", tuning: "C G B D G B D" },

  { instrument: "Sitar", name: "Standard", tuning: "C C G C G C F x C C B C D E F G A B C D E" },
]);
